# Description
* This notebook is solely used to split the dataframe into smaller csv files (under 100Mb) so I can upload onto github

In [40]:
import pandas as pd

In [41]:
clean_merge = pd.read_csv('./data/output_files/merged_df.csv') # file size is around 195Mb - so want to split into 2

In [53]:
def split_files(file_path,file_name,num_files):
    df = pd.read_csv(file_path+file_name)
    file_name_noext = file_name.split('.')[0] # get the front part of the name
    split_idx = df.shape[0]//num_files # getting the split index
    for n in range(num_files):
        if n == (num_files-1): # the last file should go to the last index
            section = clean_merge[n*split_idx:]
        else: # this will work if n=0 or anything that is not the end_file
            section = clean_merge[n*split_idx:(n+1)*split_idx]
        section_file_name = file_name_noext+str(n+1)+'.csv'
        section.to_csv(file_path+section_file_name,index=False)
    print("success")

In [54]:
split_files('./data/output_files/','merged_df.csv',2)

success

In [55]:
clean_merge.shape[0]//2

68666

In [56]:
!ls data/output_files/ -1

acc_unpack.csv
merged_df1.csv
merged_df2.csv
merged_df.csv
result_freq.csv
result_time.csv

In [63]:
files_list = ['merged_df1.csv','merged_df2.csv']
folder_link = './data/output_files/'

In [64]:
def combine_db_from_folder(folder_link,files_list):
    """
    Take in the filepath to a folder containing csv files and a list containing the csv names,
    read in the csv as dataframes
    and return a combined dataframes with a column specifying where the file comes from
    
    input:
    folder_link : the filepath of the folder containing the csv files
    files_list : a list containing the name of the files inside the folder-file name follow format "BK7610_clean_TAC.csv"
    
    output:
    combined = a pandas dataframe contanining all the entries from the different files
    """
    combined = pd.DataFrame()
    for file in files_list:
        ind_db = pd.read_csv(folder_link+file)
        combined = pd.concat([ind_db,combined])
    return combined

In [65]:
combined = combine_db_from_folder(folder_link,files_list)

In [66]:
combined.shape

(137333, 82)

In [67]:
combined.head()

,pid__x,time_,x_zerocrossings,x_entropy,x_density,x_centroids,y_zerocrossings,y_entropy,y_density,y_centroids,...,z_min,z_mean,z_median,z_var,z_kurtosis,z_skewness,z_interval,z_rms,TAC_Reading,intoxicated
0,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,0.0077,0.009498,0.00950,2.923647e-07,0.107379,0.131725,0.0034,0.009514,0.182644,1
1,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.2436,-0.002826,-0.00475,4.611911e-03,1.764429,0.208733,0.4911,0.067885,0.182644,1
2,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.2118,-0.007926,-0.00580,3.160200e-03,1.842521,-0.421897,0.3951,0.056644,0.182644,1
3,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.7261,0.006971,0.00095,3.234918e-02,3.438768,-0.559695,1.2528,0.179768,0.182644,1
4,SF3079,2017-05-02 17:58:10,72.0,5.545490,0.001192,4.493106,57.0,5.873763,0.000626,5.746770,...,-0.0137,0.016055,0.01590,4.948490e-05,39.193064,3.693956,0.1019,0.017525,0.095807,1

In [57]:
# comfirming by reading mannually
merged_df1 = pd.read_csv('./data/output_files/merged_df1.csv')
merged_df2 = pd.read_csv('./data/output_files/merged_df2.csv')

In [58]:
merged_df1.shape

(68666, 82)

In [59]:
merged_df2.shape

(68667, 82)

In [60]:
clean_merge.shape

(137333, 82)

In [61]:
merged_df1.head()

,pid__x,time_,x_zerocrossings,x_entropy,x_density,x_centroids,y_zerocrossings,y_entropy,y_density,y_centroids,...,z_min,z_mean,z_median,z_var,z_kurtosis,z_skewness,z_interval,z_rms,TAC_Reading,intoxicated
0,BK7610,2017-05-02 14:37:50,75.0,4.855201,0.000069,2.894617,97.0,6.113909,0.000093,5.835264,...,-0.1963,0.009442,0.00685,0.003249,2.994924,0.178858,0.4489,0.057704,0.052238,0
1,BK7610,2017-05-02 14:37:50,75.0,4.855201,0.000069,2.894617,97.0,6.113909,0.000093,5.835264,...,-0.6540,0.013335,0.00115,0.060221,1.002979,0.499894,1.5697,0.245455,0.052238,0
2,PC6771,2017-05-02 14:37:50,61.0,3.132623,0.003668,4.913792,51.0,3.115796,0.002053,4.876917,...,-0.1963,0.009442,0.00685,0.003249,2.994924,0.178858,0.4489,0.057704,0.059162,0
3,PC6771,2017-05-02 14:37:50,61.0,3.132623,0.003668,4.913792,51.0,3.115796,0.002053,4.876917,...,-0.6540,0.013335,0.00115,0.060221,1.002979,0.499894,1.5697,0.245455,0.059162,0
4,BK7610,2017-05-02 14:38:00,90.0,6.042793,0.000028,5.069854,97.0,5.988535,0.000057,4.987723,...,-0.2764,0.006739,0.00905,0.003207,5.684678,-0.900763,0.5099,0.056955,0.052238,0

In [62]:
merged_df2.head()

,pid__x,time_,x_zerocrossings,x_entropy,x_density,x_centroids,y_zerocrossings,y_entropy,y_density,y_centroids,...,z_min,z_mean,z_median,z_var,z_kurtosis,z_skewness,z_interval,z_rms,TAC_Reading,intoxicated
0,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,0.0077,0.009498,0.00950,2.923647e-07,0.107379,0.131725,0.0034,0.009514,0.182644,1
1,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.2436,-0.002826,-0.00475,4.611911e-03,1.764429,0.208733,0.4911,0.067885,0.182644,1
2,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.2118,-0.007926,-0.00580,3.160200e-03,1.842521,-0.421897,0.3951,0.056644,0.182644,1
3,SA0297,2017-05-02 17:58:10,42.0,5.282973,0.000615,6.113494,46.0,4.991548,0.000313,5.644283,...,-0.7261,0.006971,0.00095,3.234918e-02,3.438768,-0.559695,1.2528,0.179768,0.182644,1
4,SF3079,2017-05-02 17:58:10,72.0,5.545490,0.001192,4.493106,57.0,5.873763,0.000626,5.746770,...,-0.0137,0.016055,0.01590,4.948490e-05,39.193064,3.693956,0.1019,0.017525,0.095807,1